### PR TITLE
Added reference type constraints

### PR DESCRIPTION
**Pull request by JordyWells**

### CODE REVIEW

**Comment by jbogard** [comment]
Would it be better to have it check for `default(TNotification)`? I'm a little wary of *adding* more generic constraints.

**Comment by JordyWells** [comment]
I think that is 100% fair!

**Comment by JordyWells** [comment]
@jbogard  Just thinking, would `default(TNotification)` be correct? It means you just cant send an empty version of an `INotification` implementation. but null would still be allowed. If we constrain it to class it means that the null check would still make sense, and that `INotification` must be of a reference type. So basically don't send ints or structs. Would it make sense to actually keep the class constraint, but actually add the `default(TNotification)` check as well, and throw a different exception?

**Comment by JordyWells** [comment]
Just a second though, by checking `default(TNotification)` what if an implementations default value was actually something you did want to publish?
I think the class constraint ensuring its a reference type and not null might make the most sense?

**Comment by jbogard** [comment]
What's the purpose for the class constraint? What scenario are we trying to prevent here? Sending value types? Is that in and of itself bad?

Won't this already fail if there aren't any handlers? Or not for something like `mediator.Publish(5)`?

**Comment by JordyWells** [comment]
@jbogard You're actually correct, sending a value type like an int would already fail, but without the class constraint I can implement a struct and send that, which I don't think is wanted behavior?

**Comment by jbogard** [comment]
You can send anything, as long as there is a handler. And I already check for that and throw an exception.

**Comment by JordyWells** [comment]
Ok sounds good to me.

**Pull request closed without merging**
