### PR TITLE
#136 - remove "initialized" variable

### PR DESCRIPTION
**Pull request by swimtver**
from "GetHandler" function & make private field in RequestHandlerImpl

### CODE REVIEW

**Comment by remcoros** [comment]
This still has the issue of the handler class instantiated twice on first use as discussed here: https://github.com/jbogard/MediatR/issues/136#issuecomment-279090119

I proposed to remove the caching all together and make it work like notifications (every 'Send' goes to the container). This is discussed here: https://github.com/jbogard/MediatR/issues/126

And a (proposed fix) here: https://github.com/jbogard/MediatR/compare/master...remcoros:fix-126-remove_factory_cache?expand=1

**Comment by swimtver** [comment]
@remcoros, thanks for your answer. I believe that there is the reason, why author put handler instances and factory functions in cache. And "initialized" varailble's using looks like mistake.
 I looked at your fix, and i think it's a big change. It's gonna be design decision.

**Comment by jbogard** [comment]
I introduced the cache so that you wouldn't have exceptions on every
resolution. This is all due to me making just one IRequest interface and
determining at runtime which handler actually matches. I can't determine
that except by trying to instantiate and caching the strategy on which
handler "works" (sync/async/async w/ cancellation token).

**Comment by swimtver** [comment]
@jbogard, thanks for the detailed description. But you should look on LazyInitializer.EnsureInitialized using.
I think this code is doing not what you expected. Or I missed something?
I will try to write test to reproduce this behavior.

**Comment by P14x** [comment]
The LazyInitializer.EnsureInitialized overload being used,
uses the boolean argument - which is always false - to determine whether the target has already been initialized.
Refactoring it into a field resolves this, so that the caching strategy works.

**Comment by jbogard** [comment]
@remcoros I believe the caching would only fail for you if a user switched from one handler interface to another.

**Pull request merged**
