### PR TITLE
Added Example for Grace IoC

### PR DESCRIPTION
**Pull request by shahabganji**
Added an example of how to configure MediatR with [GraceIoC](https://github.com/ipjohnson/Grace) written by @ipjohnson.

### CODE REVIEW

**Comment by jbogard** [comment]
What is the output?

**Comment by shahabganji** [comment]
There were examples for other IOC containers regarding how to work with MediatR, but Grace. So just added an example for that.

**Comment by jbogard** [comment]
Here's the output of the capabilities from the build:

```
===============
GraceIoC
===============

Sending Ping...
- Starting Up
-- Handling Request
--- Handled Ping: Ping
-- Finished Request
- All Done with Ping
- All Done
Received: Ping Pong

Publishing Pinged...
Got pinged async.
Got pinged constrained async.
Got pinged also async.

Publishing Ponged...
Got ponged async.

Sending Jing...
- Starting Up
-- Handling Request
--- Handled Jing: Jing, no Jong
-- Finished Request
- All Done

Checking handler to catch exact exception...
- Starting Up
-- Handling Request
Exception of type 'MediatR.Examples.ExceptionHandler.ForbiddenException' was thrown.

Checking shared handler to catch exception by base type...
- Starting Up
-- Handling Request
---- Exception Handler: 'MediatR.Examples.ExceptionHandler.ConnectionExceptionHandler'

Checking base handler to catch any exception...
- Starting Up
-- Handling Request
A task was canceled.

Selecting preferred handler to handle exception...
- Starting Up
-- Handling Request
---- Exception Handler: 'MediatR.Examples.ExceptionHandler.Overrides.CommonExceptionHandler'

Selecting new handler to handle exception...
- Starting Up
-- Handling Request
---- Exception Handler: 'MediatR.Examples.ExceptionHandler.Overrides.ServerExceptionHandler'

---------------
Request Handler....................................................Y
Void Request Handler...............................................Y
Pipeline Behavior..................................................Y
Pre-Processor......................................................Y
Post-Processor.....................................................Y
Constrained Post-Processor.........................................Y
Ordered Behaviors..................................................Y
Notification Handler...............................................Y
Notification Handlers..............................................Y
Constrained Notification Handler...................................Y
Covariant Notification Handler.....................................N
Handler for inherited request with same exception used.............N
Handler for inherited request with base exception used.............N
Handler for request with less specific exception used by priority..N
Preferred handler for inherited request with base exception used...N
Overridden handler for inherited request with same exception used..N
```

**Comment by ipjohnson** [comment]
@jbogard I'm not super familiar with MediatR, what specific feature are needed for the inherited request/exceptions? Is it just a matter of enabling covariant behavior?

**Comment by shahabganji** [comment]
@jbogard Oh my bad, I thought you meant the outcome/benefits 🤦🏼

**Pull request closed without merging**
