### PR TITLE
[Draft] Feature/extendable

### PR DESCRIPTION
**Pull request by driekus77**
Possible alternative for #574

### CODE REVIEW

**Comment by rodion-m** [comment]
@jbogard It's impossible to use MediatR + gRPC streaming without `IAsyncEnumerable` response supporting. Please review and merge it.

**Comment by Tinkvision** [comment]
Any new about this feature ? 
That is really a good job and nice improvement ;)

**Comment by driekus77** [comment]
Dear @jbogard / all,

Is there any change in near future this IAsyncEnumerable PR gets through? Is there something missing? 

I'm already investigating alternatives like MessagePipe (https://github.com/Cysharp/MessagePipe)  and Brighter (https://www.goparamore.io/).
But they seem bloated: To much features for what I need.

Hope to hear from you.

Kind regards,

Henry

**Comment by driekus77** [comment]
The original PR https://github.com/jbogard/MediatR/pull/574  has come through. Leaving this PR unwanted/needed.

Closing...

**Pull request closed without merging**
