### PR TITLE
Contravariance fix for INotificationHandler<>

### PR DESCRIPTION
**Pull request by henkmollema**
Also the `IAsyncNotificationHander<>`. 
Updated Simple Injector to v2.7.0-beta1.

This fix makes sure that the `GenericHandler` is resolved too when requesting:
```csharp
container.Resolve<INotificationHandler<Pinged>>();
```
Also see: http://stackoverflow.com/questions/27909866

Console output:
```
Sample mediator implementation using send, publish and post-request handlers in
sync and async version.
---------------
Sending Ping...
Received: Ping Pong
Sending Ping async...
Received async: Ping Pong
Publishing Pinged...
Got notified.      <-- this one is from the GenericHandler.
Got pinged.
Got pinged also.
Publishing Pinged async...
Got pinged async.
Got pinged also async.
```

### CODE REVIEW

**Comment by jbogard** [comment]
So is this only available in the beta?

**Comment by henkmollema** [comment]
Yes, it was a limitation/bug in Simple Injector according to Steven.

**Comment by jbogard** [comment]
I'm going to wait on this for the release version then - this is intended to show folks how to set up MediatR in their apps, and relying on a beta version would invite more questions to me on "how do I do this in v2.6". Or something.

**Comment by henkmollema** [comment]
I understand. I'll push again when it's released.

**Comment by henkmollema** [comment]
With the latest version (v2.7.0-beta2) `RegisterManyForOpenGeneric` is fixed and works appropriately, making this PR unnecessary. I'll create a new one when the beta is released.

**Pull request closed without merging**
