### PR TITLE
[WIP] Restructure repository and port every project to project.json

### LINKED ISSUE #59: CoreCLR
Is this supposed to work on coreclr? I've tried to get it to build but no joy :cry:

### PR DESCRIPTION
**Pull request by khellang**
This PR ports all projects to project.json. Every project builds and all the examples runs :sparkles:

The main project targets `net40` and `dotnet5.1`. This should cover just about everything and the kitchen sink. 

All the demo projects target `dnx451` and `dnxcore50`, exept the following, because their containers doesn't support `dnxcore50` yet:
 - Windsor
 - Unity
 - Ninject

Currently, the tests doesn't run because Fixie doesn't support running from DNX yet. It's a pretty quick task to port them to xUnit, though.

Let me know what you think :smile:

Fixes #59

### CODE REVIEW

**Comment by jbogard** [comment]
Drop .NET 4.0, in favor of 4.5.1? I don't know why I added it in the first place.

**Comment by khellang** [comment]
4.5.1 is [already covered by `dotnet5.1`](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md) (see `netstandard1.0` which is the same). It's no problem having .NET 4.0 there... But I guess it's no point in supporting it?

**Comment by jchannon** [comment]
merge, merge, merge :smile:

**Comment by jchannon** [comment]
@khellang does this need the dotnet/cli tools?

**Comment by khellang** [comment]
Nope. All the existing tooling (DNVM/DNX/DNU etc.)

**Comment by khellang** [comment]
Should get a AppVeyor/Travis CI build up and running for this.

**Comment by jbogard** [comment]
AppVeyor for sure, I just got my other projects going there. I hesitated on dropping net451 because I've had reports of issues of ONLY having dotnet5.1, and I assume once netstandard becomes...standard then those issues will go away.

**Comment by khellang** [comment]
Alright. I added a net45 target as well. It looks like MS has net45 targets for a lot of their packages in addition to `dotnet5.x` :+1:

**Comment by jbogard** [comment]
Is this one ready to go? When this comes in I'm going to add an actual build script

**Comment by khellang** [comment]
Yep, I think so. I have a couple of scripts for Travis (bash) and AppVeyor (PoSH) lying around. They pull down the DNX version specified in global.json for both CLR and CoreCLR, restore, build, test (for both platforms) and pack the projects. I'll add them as gists if you're interested :smile:

**Comment by khellang** [comment]
@jbogard what's your thoughts on the tests?

**Comment by jbogard** [comment]
@plioi I'll let you handle this one

**Comment by plioi** [comment]
@jbogard @khellang The xUnit team has been more adventurous with the moving target of .NET Core.  Fixie will get there, but I admit I'm behind on that learning curve.  In the interest of letting Mediatr move forward with this PR, I'd recommend a quick port to xUnit, if only for the time being.

**Pull request merged**
