### PR TITLE
Applied the newer code analysis rules.

### PR DESCRIPTION
**Pull request by jscarle**
Starting with .NET 5, there are new [code analysis rules](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#code-analysis-properties) being shipped with each release of the .NET SDK.

Since they're mostly straightforward fixes, I addressed the following rules:
- [CA1002: Do not expose generic lists](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1002) 
- [CA1062: Validate arguments of public methods](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1062) 
- [CA1859: Use concrete types when possible for improved performance](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1859) 
- [CA1852: Seal internal types](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1852) 
- [CA1860: Avoid using 'Enumerable.Any()' extension method](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1860) 
- [CA2007: Do not directly await a Task](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca2007)

Due to the nature of the project, some rules wouldn't make sense, therefore I muted the following rules:
- [CA1031: Do not catch general exception types](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1031)
- [CA1040: Avoid empty interfaces](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1040)
- [CA1307: Specify StringComparison for clarity](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1307)
- [CA1711: Identifiers should not have incorrect suffix](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1711)
- [CA1716: Identifiers should not match keywords](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1716)
- [CA1812: Avoid uninstantiated internal classes](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1812)

I also did a minor cleanup of small warnings. Each step was done as a separate commit to facilitate the code review.

### CODE REVIEW

**Comment by jscarle** [comment]
@jbogard Can you take a look a this when you have a moment?

**Comment by jscarle** [comment]
I can't seem to remove the stale tag.

**Comment by jbogard** [comment]
The Contracts project can't be changed. Or at least, these changes aren't critical enough for me to update a package I've said will never be changed 🤣

**Comment by jscarle** [comment]
@jbogard Sorry about that, it was an oversight on my end. I've removed any changes to the Contracts project.

**Pull request closed without merging**
