### PR TITLE
Removed CancellableAsync handlers

### PR DESCRIPTION
**Pull request by danielmarbach**
This is a proposal PR. I think the `CancellableAsyncRequestHandler` is just unnecessary noise. It is kinda handy to always have a `CancellationToken` in the scope of the handle method. By using `default(CancellationToken)` you get `CancellationToken.None`.

This would be a major breaking change. If you like it I rebase and add the two failing tests

### CODE REVIEW

**Comment by jbogard** [comment]
Yeah that is a breaking change. It's probably the right one though, since users are calling the handlers from their application code directly, rather than like NSB with the framework calling it.

**Comment by danielmarbach** [comment]
Should I finish it?

Do you use any kind of obsoletion techniques?

**Comment by khellang** [comment]
I actually PR'd this quite a while ago (#40), but was asked to  split it out as a separate interface (#44). Are we going back on this now? If so, :+1: from me.

**Comment by jbogard** [comment]
Not really for this library - I just rev to 3.0. Once merged I'd modify the project.json. 

One thing that worries me are default param values, those don't version, but I don't see them changing

**Comment by danielmarbach** [comment]
@khellang history repeats itself

**Comment by danielmarbach** [comment]
So what's up with this?

**Comment by jbogard** [comment]
Can you rebase?

**Comment by abatishchev** [comment]
@danielmarbach ping

**Comment by danielmarbach** [comment]
Hopefully I can rebase after my vacation (approx. 1 week)

**Comment by abatishchev** [comment]
@danielmarbach can you please rebase?

**Comment by danielmarbach** [comment]
rebasing right now

**Comment by danielmarbach** [comment]
Rebased

**Comment by khellang** [comment]
There's a failing test; `MediatR.Tests.AsyncPublishCancelTests.Should_throw_cancelled`

**Comment by danielmarbach** [comment]
Wow this was a crappy experience. Shouldly doesn't have a ThrowsAsync on .net standard so I had to trick around that  a bit

**Comment by danielmarbach** [comment]
Green, green, green...

**Comment by jbogard** [comment]
OK the way I'm thinking of going here with 3.0 is including the pipeline as part of the MediatR setup, which would mean I would standardize a pipeline, but not worry about the individual kinds of handlers.

**Pull request closed without merging**
