### PR TITLE
LightInject implementation

### PR DESCRIPTION
**Pull request by vegar**
I have tried to follow the patterns from the other examples, but I'm not sure it gives the answers you want for the blog post.

### CODE REVIEW

**Comment by jbogard** [comment]
When you run the app, what does it print out?

**Comment by vegar** [comment]
````¨
Sample mediator implementation using send, publish and post-request handlers in
sync and async version.
---------------
Sending Ping...
Received: Ping Pong
Sending Ping async...
Received async: Ping Pong
Publishing Pinged...
Got pinged.
Got pinged also.
Publishing Pinged async...
Got pinged async.
Got pinged also async.

````

**Comment by jbogard** [comment]
So no variance support then?

**Comment by vegar** [comment]
Well, here's the point where I'm not sure the example really gave the answers it should... I'm completely open for the idea that I have done something wrong..

I know LightInject suports generics to some extents. I can register a generic handler, and then ask it to resolve a concrete instance like this:

    container.Register(typeof(IRequestHandler<,>, GenericRequestHandler<,>);
    var instance = container.GetInstance<IRequestHandler<Ping, Pong>>();

but this want work:

   container.Register(typeof(IRequestHandler<, >), typeof(PingHandler));
   var instance = container(GetInstance<IRequestHandler<Ping, Pong>>();

neither do this:

   container.Register(typeof(PingHandler));
   var instance = container.GetInstance<IRequestHandler<Ping, Pong>>();

**Comment by henkmollema** [comment]
Basically,
```csharp
serviceContainer.GetAllInstances<INotificationHandler<Pinged>>()
```
should resolve `GenericHandler`, `PingedHandler` and `PingedAlsoHandler`.

Right now, it does not resolve the `GenericHandler`. I can't find anything in [the docs](http://www.lightinject.net/#toc22) which allows explicit registration of contravariance types like Simple Injector does with `RegisterManyForOpenGeneric`.

**Comment by vegar** [comment]
The author of LightInject has released a new version which resolves all three handlers:

````
Sample mediator implementation using send, publish and post-request handlers in
sync and async version.
---------------
Sending Ping...
Received: Ping Pong
Sending Ping async...
Received async: Ping Pong
Publishing Pinged...
Got notified.
Got pinged.
Got pinged also.
Publishing Pinged async...
Got notified also async.
Got pinged async.
Got pinged also async.
````

Does this look more like it?

**Comment by jbogard** [comment]
Yep. Can you update your PR with the version that works, and I'll merge it in. Thanks!

**Comment by vegar** [comment]
The PR is already up to date. 

Mvh,
-Vegar

**Pull request merged**
