### PR TITLE
Updated LightInject to 5.1.2 adding support for ordered services

### PR DESCRIPTION
**Pull request by seesharper**
This PR updates LightInject to 5.1.2 adding support for ordered services.
This should complete the score card for for LightInject 👍

### CODE REVIEW

**Comment by dadhi** [comment]
Interesting, so the order of registrations themselves is not enough?

**Comment by seesharper** [comment]
@dadhi Scanning an assembly is probably not going to bring back types in a deterministic way, so I figured an explicit API for dealing with the ordering was the best choice, at least for LightInject :)

**Comment by dadhi** [comment]
OK, then just the clarity and discoverability.. nice.

**Comment by jbogard** [comment]
It looks like this results in double publishing? https://ci.appveyor.com/project/jbogard/mediatr/build/93-eamslrgn#L237

**Comment by seesharper** [comment]
@jbogard Should be good now 👍

**Pull request merged**
