### PR TITLE
Partially fix #819

### LINKED ISSUE #819: (Bug) Contravariant handler is not resolved from Microsoft.DI service provider
## Related
https://stackoverflow.com/questions/54922190/microsoft-dependency-injection-and-contravariance

Microsoft wont fix: https://github.com/aspnet/DependencyInjection/issues/453

## Reproduction
https://github.com/tvardero/mediatr-contravariance

### Contracts
```csharp
record PaintCarCommandBase : INotification
{
    public required string Color { get; init; }
}

record PaintTeslaCommand : PaintCarCommandBase { }

record PaintToyotaCommand : PaintCarCommandBase
{
    public required string SecondaryColor { get; init; }
}
```

### Handlers
```csharp
abstract class CommandHandlerBase<TCommand> : INotificationHandler<TCommand>
where TCommand : INotification
{
    public abstract Task Handle(TCommand command, CancellationToken cancel);
    // do some logging here, command validation, etc
    // or maybe make this CommandHandlerBase reused also by RabbitMq
}

class PaintCarCommandHandler : CommandHandlerBase<PaintCarCommandBase>
{
    public override Task Handle(PaintCarCommandBase command, CancellationToken cancel)
    {
        Console.WriteLine($"Painting car using primary color: {command.Color}");

        if (command is PaintToyotaCommand toyotaCommand)
        {
            Console.WriteLine($"Painting spoilers using secondary color: {toyotaCommand.SecondaryColor}");
        }

        return Task.CompletedTask;
    }
}
```

### The Code
```csharp
serviceCollection.AddMediatR(Assembly.GetExecutingAssembly());

using var serviceProvider = serviceCollection.BuildServiceProvider();

var toyotaPainting = new PaintToyotaCommand { Color = "black", SecondaryColor = "red" };
var teslaPainting = new PaintTeslaCommand { Color = "bright pink" };

var mediator = serviceProvider.GetRequiredService<IMediator>();

mediator.Publish(toyotaPainting); // <-- unfortunately does nothing
mediator.Publish(teslaPainting); // <-- unfortunately does nothing

var h1 = serviceProvider.GetService<INotificationHandler<PaintCarCommandBase>>(); // <-- not null, OK
var h2 = serviceProvider.GetService<INotificationHandler<PaintToyotaCommand>>(); // <-- Null
var h3 = serviceProvider.GetService<INotificationHandler<PaintTeslaCommand>>(); // <-- Null

Console.ReadLine();
```

## How MediatR could fix that
I have investigated some source code and found something. Lets say we are handling Toyota painting.

This line creates NotificationHandlerWrapper with type of PaintToyotaCommand.
https://github.com/jbogard/MediatR/blob/09dbb3e8c5c58b6e949e06e57755211571efda48/src/MediatR/Mediator.cs#L110

Later, wrapper attempts to find handlers of type `INotificationHandler<PaintToyotaCommand>`:
https://github.com/jbogard/MediatR/blob/09dbb3e8c5c58b6e949e06e57755211571efda48/src/MediatR/Wrappers/NotificationHandlerWrapper.cs#L26

And as we saw earlier, this returns null as Microsoft.DI does not support contravariance.

The fix could be simple, find INotificationHandler for base class too (recursive), if it is also marked with `INotification` interface.

### PR DESCRIPTION
**Pull request by tvardero**
For contravariant `INotification`.
For IRequest and IStreamRequest i would like to get some help

### CODE REVIEW

**Comment by tvardero** [comment]
I'll try with requests and streamrequests tomorrow to do all of that in one go

**Comment by tvardero** [comment]
Waiting for review

**Comment by jbogard** [comment]
Can you write some tests? I'm not sure what cases this is fixing.

**Comment by tvardero** [comment]
Yes, I'll do, however I'll be able to next week

**Comment by tvardero** [comment]
I'll reopen PR

**Pull request closed without merging**
